In [10]:
import pandas as pd
import numpy as np

path = r"/Users/gustavetriomphe/Desktop/HEC/interpretability-stability-fairness/dataproject2025.csv"
df = pd.read_csv(path)

In [21]:
df['Index'] = df['Unnamed: 0']
df = df.drop(columns=['Unnamed: 0'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1086683 entries, 0 to 1086682
Data columns (total 39 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   issue_d                  1086236 non-null  float64
 1   loan duration            1086236 non-null  float64
 2   annual_inc               1086236 non-null  float64
 3   avg_cur_bal              1086236 non-null  float64
 4   bc_open_to_buy           1086236 non-null  float64
 5   bc_util                  1086236 non-null  float64
 6   delinq_2yrs              1086236 non-null  float64
 7   dti                      1086236 non-null  float64
 8   emp_length               1086236 non-null  object
 9   emp_title                1086236 non-null  object
 10  fico_range_high          1086236 non-null  float64
 11  funded_amnt              1086236 non-null  float64
 12  grade                    1086236 non-null  object
 13  home_ownership           1086236 non-null  object
 14  inq_last_6mths           1086236 non-null  float64
 15  int_rate                 1086236 non-null  float64
 16  mo_sin_old_rev_tl_op     1086236 non-null  float64
 17  mo_sin_rcnt_rev_tl_op    1086236 non-null  float64
 18  mo_sin_rcnt_tl           1086236 non-null  float64
 19  mort_acc                 1086236 non-null  float64
 20  mths_since_recent_bc     1086236 non-null  float64
 21  num_actv_bc_tl           1086236 non-null  float64
 22  num_bc_tl                1086236 non-null  float64
 23  num_il_tl                1086236 non-null  float64
 24  num_rev_accts            1086236 non-null  float64
 25  open_acc                 1086236 non-null  float64
 26  pub_rec                  1086236 non-null  float64
 27  pub_rec_bankruptcies     1086236 non-null  float64
 28  purpose                  1086236 non-null  object
 29  revol_bal                1086236 non-null  float64
 30  revol_util               1086236 non-null  float64
 31  sub_grade                1086236 non-null  object
 32  target                   1086236 non-null  float64
 33  tax_liens                1086236 non-null  float64
 34  zip_code                 1086236 non-null  float64
 35  Pct_afro_american        1086236 non-null  float64
 36  Predictions              1086236 non-null  float64
 37  Predicted probabilities  1086236 non-null  float64
 38  Index                    1086683 non-null  int64
dtypes: float64(32), int64(1), object(6)
memory usage: 323.3+ MB

In [15]:
# number of missing values
number_missing_values = df.isna().sum().sum()
print(f"Number of missing values: {number_missing_values}")
# drop rows with missing values
df.dropna()

Number of missing values: 16986

,Unnamed: 0,issue_d,loan duration,annual_inc,avg_cur_bal,bc_open_to_buy,bc_util,delinq_2yrs,dti,emp_length,...,purpose,revol_bal,revol_util,sub_grade,target,tax_liens,zip_code,Pct_afro_american,Predictions,Predicted probabilities
0,0,2013.0,0.0,39600.0,1379.0,21564.0,16.1,0.0,2.49,2 years,...,home_improvement,4136.0,16.1,B2,0.0,0.0,782.0,7.388592,0.0,0.053051
1,1,2013.0,0.0,55000.0,9570.0,16473.0,53.9,0.0,22.87,10+ years,...,debt_consolidation,36638.0,61.2,B2,0.0,0.0,481.0,9.745456,0.0,0.084507
2,2,2013.0,0.0,325000.0,53306.0,13901.0,67.1,0.0,18.55,5 years,...,debt_consolidation,29581.0,54.6,A3,0.0,0.0,945.0,7.542862,0.0,0.037206
3,3,2013.0,0.0,130000.0,36362.0,3567.0,93.0,0.0,13.03,10+ years,...,debt_consolidation,10805.0,67.0,B3,0.0,0.0,809.0,6.598132,0.0,0.061371
4,4,2013.0,1.0,73000.0,24161.0,4853.0,74.7,1.0,23.13,6 years,...,debt_consolidation,27003.0,82.8,D5,1.0,0.0,802.0,7.058900,1.0,0.345896
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1085784,1086231,2017.0,0.0,75000.0,4419.0,19337.0,49.0,0.0,23.25,10+ years,...,debt_consolidation,21894.0,39.9,B5,0.0,0.0,333.0,30.375294,0.0,0.243743
1085785,1086232,2017.0,0.0,95000.0,27902.0,14788.0,76.0,1.0,17.60,< 1 year,...,debt_consolidation,47135.0,74.9,C4,0.0,0.0,917.0,4.026823,1.0,0.456995
1085786,1086233,2017.0,1.0,150457.2,22619.0,303.0,90.5,0.0,19.62,10+ years,...,home_improvement,11977.0,81.5,C5,0.0,0.0,201.0,8.916837,0.0,0.081101
1085787,1086234,2017.0,0.0,150000.0,11837.0,4347.0,92.6,0.0,26.03,10+ years,...,credit_card,56467.0,81.4,C1,0.0,0.0,535.0,2.617934,0.0,0.150079
1085788,1086235,2017.0,1.0,85000.0,6043.0,10943.0,50.7,2.0,8.56,1 year,...,other,12830.0,44.7,C1,0.0,0.0,210.0,15.186997,1.0,0.379079

In [9]:
outputs = df['Predicted probabilities']
predictions = df['Predictions']
true_labels = df['target']